### ISSUE TITLE
Rename Unboxed to Result

### ISSUE THREAD

**Issue by schickling** [terhechte/CoreValue#2]
I think using the `Result` type instead of `Unboxed` would be more Swift idiomatic.

See: http://radex.io/swift/error-conversions/

**Comment by terhechte** [comment]
Yeah, definitely. However, one of the Swift Compiler guys recently shared on Twitter that they'll allow full access to the underlying `Either` type of the current Swift 2 exceptions. So instead of using `throw/try/catch` for error handling, one could also receive an `Either<Result, Error>` type. I'm not sure if they're still planning to do that, but I'm currently hoping and waiting for that to happen and will then switch to that official Either type. If that doesn't come with the official Swift 2.0, I'll probably go and embed the `Result` microframework instead :)

**Comment by schickling** [comment]
Perfect! Glad to hear that!

**Comment by blender** [comment]
@schickling would you consider using https://github.com/typelift/Swiftz for custom operators and the like?

**Comment by terhechte** [comment]
@blender Hey, I thought about this for some time and I think I'd rather keep the dependencies low. However, you're right that having custom operators for various packages makes things difficult to use. I'm considering switching to `try/catch` as well as removing most of the custom operators (or adding simple function alternatives) to make it easier to start using this.

**Comment by terhechte** [comment]
I'll close this now as we have support for try / catch instead of Result / Unbox.
