### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by schickling** [terhechte/CoreValue#3]
Are there any iOS9+ features used? Otherwise it would be nice if this package would be available for iOS8 as well! :+1:

**Comment by terhechte** [comment]
In general, the binaries created by Swift 2 are not compatible with the binaries created in Swift 1.2. So you won't be able to use CoreValue in any Xcode 6.x project. However, taking an iOS 8 app into Xcode 7 and then adding CoreValue, I would have thought that this works, but it seems it doesn't. This may be a temporary Xcode 7 issue, or I may have done something wrong, but I've just tried the following: I've installed the iOS 8.4 Simulator in Xcode 7. Then I created a new test project in Xcode 7 with a deployment target of Xcode 8.4. Then I selected the iOS 8.4 Simulator (iPhone 5s), and when I then tried to compile and run the code in the Simulator, `swiftc` crashed with:

`Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

The command in question contains this line: `-sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -target x86_64-apple-ios8.4`. So it seems selecting iOS 8.4 worked, but compiling against it doesn't work. Which is weird, as the binary should be the same if only the deployment target fails and not the SDK. I'll try running the app on an iOS 8 device tomorrow to see if that somehow works, because apparently Swift 2 apps should run fine under iOS 8.

**Comment by schickling** [comment]
I'm currently developing an iOS8.4 app using Swift 2. So it definitely IS possible. :+1:

**Comment by adly-holler** [comment]
+1

**Comment by Shirk** [comment]
:+1: this issue is all that keeps me from going all in on CoreValue.

**Comment by terhechte** [comment]
I'll close this now as I think that iOS9 compatibility should be sufficient now, with iOS 10 already widely deployed :)
